[INFO    :   django.utils.autoreload] - 2024-01-14 14:26:21,197 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-14 14:26:23,517 : log_response @0241: Not Found: /
[WARNING :             django.server] - 2024-01-14 14:26:23,517 : log_message @0212: "GET / HTTP/1.1" 404 2167
[WARNING :            django.request] - 2024-01-14 14:26:23,764 : log_response @0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-14 14:26:23,767 : log_message @0212: "GET /favicon.ico HTTP/1.1" 404 2218
[DEBUG   :               app_1.views] - 2024-01-14 14:26:45,133 : index @0022: Index page requested.
[INFO    :             django.server] - 2024-01-14 14:26:45,134 : log_message @0212: "GET /hw_1/ HTTP/1.1" 200 284
[DEBUG   :               app_1.views] - 2024-01-14 14:27:46,224 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-14 14:27:46,224 : log_message @0212: "GET /hw_1/about/ HTTP/1.1" 200 266
[INFO    :   django.utils.autoreload] - 2024-01-14 14:49:43,235 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-14 14:49:48,968 : log_response @0241: Not Found: /
[WARNING :             django.server] - 2024-01-14 14:49:48,969 : log_message @0212: "GET / HTTP/1.1" 404 2167
[DEBUG   :               app_1.views] - 2024-01-14 14:50:13,040 : index @0022: Index page requested.
[INFO    :             django.server] - 2024-01-14 14:50:13,041 : log_message @0212: "GET /hw_1/ HTTP/1.1" 200 284
[DEBUG   :               app_1.views] - 2024-01-14 14:54:12,327 : index @0022: Index page requested.
[INFO    :             django.server] - 2024-01-14 14:54:12,328 : log_message @0212: "GET /hw_1/ HTTP/1.1" 200 284
[INFO    :   django.utils.autoreload] - 2024-01-23 17:30:50,663 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-23 17:31:01,659 : log_response @0241: Not Found: /
[WARNING :             django.server] - 2024-01-23 17:31:01,660 : log_message @0212: "GET / HTTP/1.1" 404 2274
[WARNING :            django.request] - 2024-01-23 17:31:01,751 : log_response @0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-23 17:31:01,752 : log_message @0212: "GET /favicon.ico HTTP/1.1" 404 2325
[INFO    :             django.server] - 2024-01-23 17:32:03,180 : log_message @0212: "GET /hw_2_3 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:32:03,199 : log_message @0212: "GET /hw_2_3/ HTTP/1.1" 200 3646
[WARNING :            django.request] - 2024-01-23 17:32:17,316 : log_response @0241: Not Found: /
[WARNING :             django.server] - 2024-01-23 17:32:17,317 : log_message @0212: "GET / HTTP/1.1" 404 2274
[INFO    :   django.utils.autoreload] - 2024-01-23 17:34:10,686 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\homeworks\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:34:11,361 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:34:14,739 : log_message @0212: "GET / HTTP/1.1" 200 3646
[INFO    :             django.server] - 2024-01-23 17:34:16,175 : log_message @0212: "GET / HTTP/1.1" 200 3646
[INFO    :             django.server] - 2024-01-23 17:34:17,354 : log_message @0212: "GET / HTTP/1.1" 200 3646
[INFO    :             django.server] - 2024-01-23 17:34:19,056 : log_message @0212: "GET /shop/clients HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:34:19,077 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3701
[INFO    :             django.server] - 2024-01-23 17:34:35,222 : log_message @0212: "GET /shop/products HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:34:35,243 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5304
[INFO    :             django.server] - 2024-01-23 17:34:51,701 : log_message @0212: "GET /shop/orders HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:34:51,708 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3950
[WARNING :            django.request] - 2024-01-23 17:35:00,166 : log_response @0241: Not Found: /about_me
[WARNING :             django.server] - 2024-01-23 17:35:00,167 : log_message @0212: "GET /about_me HTTP/1.1" 404 3742
[INFO    :             django.server] - 2024-01-23 17:35:09,994 : log_message @0212: "GET /admin HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:35:10,015 : log_message @0212: "GET /admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-23 17:35:10,120 : log_message @0212: "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
[INFO    :             django.server] - 2024-01-23 17:35:10,427 : log_message @0212: "GET /static/admin/css/login.css HTTP/1.1" 200 958
[INFO    :             django.server] - 2024-01-23 17:35:10,429 : log_message @0212: "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
[INFO    :             django.server] - 2024-01-23 17:35:10,433 : log_message @0212: "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[INFO    :             django.server] - 2024-01-23 17:35:10,434 : log_message @0212: "GET /static/admin/css/base.css HTTP/1.1" 200 21544
[INFO    :             django.server] - 2024-01-23 17:35:10,435 : log_message @0212: "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
[INFO    :             django.server] - 2024-01-23 17:35:10,444 : log_message @0212: "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
[INFO    :             django.server] - 2024-01-23 17:35:10,458 : log_message @0212: "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[INFO    :   django.utils.autoreload] - 2024-01-23 17:38:52,622 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\homeworks\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:38:53,311 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:38:57,918 : log_message @0212: "GET /about_me HTTP/1.1" 301 0
[DEBUG   :               app_1.views] - 2024-01-23 17:38:57,924 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 17:38:57,924 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[DEBUG   :               app_1.views] - 2024-01-23 17:39:20,233 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 17:39:20,234 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[DEBUG   :               app_1.views] - 2024-01-23 17:41:33,178 : index @0022: Index page requested.
[INFO    :             django.server] - 2024-01-23 17:41:33,180 : log_message @0212: "GET / HTTP/1.1" 200 279
[INFO    :   django.utils.autoreload] - 2024-01-23 17:42:15,325 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_1\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:42:16,069 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:42:19,110 : log_message @0212: "GET / HTTP/1.1" 200 3646
[DEBUG   :               app_1.views] - 2024-01-23 17:42:22,988 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 17:42:22,989 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[INFO    :             django.server] - 2024-01-23 17:42:27,485 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3701
[INFO    :             django.server] - 2024-01-23 17:42:53,386 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5304
[INFO    :             django.server] - 2024-01-23 17:54:19,445 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5956
[INFO    :             django.server] - 2024-01-23 17:55:23,304 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5956
[WARNING :            django.request] - 2024-01-23 17:55:33,765 : log_response @0241: Not Found: /shop/choice_product_id_form
[WARNING :             django.server] - 2024-01-23 17:55:33,765 : log_message @0212: "GET /shop/choice_product_id_form HTTP/1.1" 404 3867
[INFO    :             django.server] - 2024-01-23 17:56:58,292 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5674
[INFO    :             django.server] - 2024-01-23 17:57:08,285 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3668
[WARNING :            django.request] - 2024-01-23 18:08:13,355 : log_response @0241: Not Found: /shop/choice_products_by_client_by_days
[WARNING :             django.server] - 2024-01-23 18:08:13,356 : log_message @0212: "GET /shop/choice_products_by_client_by_days HTTP/1.1" 404 3900
[DEBUG   :               app_1.views] - 2024-01-23 18:08:19,310 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 18:08:19,311 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[INFO    :             django.server] - 2024-01-23 18:08:24,066 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3668
[INFO    :             django.server] - 2024-01-23 18:13:06,075 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3886
[INFO    :   django.utils.autoreload] - 2024-01-23 18:20:39,773 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:20:40,477 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-23 18:20:47,759 : log_response @0241: Not Found: /shop/choice_products_by_client_by_days
[WARNING :             django.server] - 2024-01-23 18:20:47,759 : log_message @0212: "GET /shop/choice_products_by_client_by_days HTTP/1.1" 404 3900
[INFO    :             django.server] - 2024-01-23 18:22:55,974 : log_message @0212: "GET /shop/client_products_sorted/3/7 HTTP/1.1" 301 0
[ERROR   :            django.request] - 2024-01-23 18:22:56,110 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 82, in client_products_sorted
    orders = Order.objects.filter(buyer=client, date_create_order__range=(before, now)).all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1484, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1296, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1761, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'buyer' into field. Choices are: client, client_id, id, order_date, order_sum, product, product_id
[ERROR   :             django.server] - 2024-01-23 18:22:56,114 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 121886
[ERROR   :            django.request] - 2024-01-23 18:25:36,374 : log_response @0241: Internal Server Error: /shop/client_orders/3
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 57, in client_orders
    orders = Order.objects.filter(buyer=client).all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1484, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1296, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1761, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'buyer' into field. Choices are: client, client_id, id, order_date, order_sum, product, product_id
[ERROR   :             django.server] - 2024-01-23 18:25:36,377 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 500 120122
[INFO    :             django.server] - 2024-01-23 18:25:43,975 : log_message @0212: "GET / HTTP/1.1" 200 3360
[INFO    :             django.server] - 2024-01-23 18:25:46,851 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3882
[INFO    :   django.utils.autoreload] - 2024-01-23 18:32:28,940 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:32:29,612 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:32:43,346 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 82, in client_products_sorted
    orders = Order.objects.filter(client=client, date_create_order__range=(before, now)).all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1484, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1296, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1761, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_create_order' into field. Choices are: client, client_id, id, order_date, order_sum, product, product_id
[ERROR   :             django.server] - 2024-01-23 18:32:43,350 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 122685
[INFO    :   django.utils.autoreload] - 2024-01-23 18:40:47,098 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:40:47,692 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:40:52,169 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.products.all()
AttributeError: 'Order' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-23 18:40:52,170 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76103
[ERROR   :            django.request] - 2024-01-23 18:41:02,451 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.products.all()
AttributeError: 'Order' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-23 18:41:02,452 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76101
[INFO    :   django.utils.autoreload] - 2024-01-23 18:42:31,578 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:42:32,128 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:42:36,628 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.product.all()
AttributeError: 'Product' object has no attribute 'all'
[ERROR   :             django.server] - 2024-01-23 18:42:36,630 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76089
[INFO    :   django.utils.autoreload] - 2024-01-23 18:46:43,990 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:46:44,576 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 18:48:03,348 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:48:03,560 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.product.all()
AttributeError: 'Product' object has no attribute 'all'
[ERROR   :             django.server] - 2024-01-23 18:48:03,560 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76087
[INFO    :   django.utils.autoreload] - 2024-01-23 18:49:45,098 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:49:45,737 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:49:47,006 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.products.all()
AttributeError: 'Order' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-23 18:49:47,008 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76103
[INFO    :   django.utils.autoreload] - 2024-01-23 18:50:49,887 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:50:50,434 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:50:53,481 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.product.all()
AttributeError: 'Product' object has no attribute 'all'
[ERROR   :             django.server] - 2024-01-23 18:50:53,482 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76089
[INFO    :   django.utils.autoreload] - 2024-01-23 18:53:48,417 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:53:49,031 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:53:52,215 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 85, in client_products_sorted
    for product in products:
TypeError: 'Product' object is not iterable
[ERROR   :             django.server] - 2024-01-23 18:53:52,217 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76056
[INFO    :   django.utils.autoreload] - 2024-01-23 18:56:25,860 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:58:20,788 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 18:58:24,827 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 200 3370
[INFO    :   django.utils.autoreload] - 2024-01-23 19:07:59,628 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 19:08:09,648 : log_message @0212: "GET /shop/client_products_sorted/3/1/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:08:43,656 : log_message @0212: "GET /shop/client_products_sorted/3/4/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:08:53,670 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:09:01,738 : log_message @0212: "GET /shop/client_products_sorted/3/1/ HTTP/1.1" 200 3490
[INFO    :   django.utils.autoreload] - 2024-01-23 19:12:38,642 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 19:12:45,004 : log_message @0212: "GET /shop/client_products_sorted/3/1/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:12:55,389 : log_message @0212: "GET /shop/client_products_sorted/3/5/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:13:04,317 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:13:21,575 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3492
[INFO    :             django.server] - 2024-01-23 19:14:08,470 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3372
[INFO    :             django.server] - 2024-01-23 19:14:09,241 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3372
[INFO    :             django.server] - 2024-01-23 20:24:05,861 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3248
[INFO    :             django.server] - 2024-01-23 20:24:47,306 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3074
[INFO    :   django.utils.autoreload] - 2024-01-23 20:37:28,431 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 20:37:29,125 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 20:51:06,366 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 20:51:11,084 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3434
[INFO    :   django.utils.autoreload] - 2024-01-23 20:59:31,046 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 20:59:31,678 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 21:04:08,587 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:04:24,689 : log_message @0212: "GET /shop/client_products_sorted/3/0/ HTTP/1.1" 200 3072
[INFO    :             django.server] - 2024-01-23 21:04:33,768 : log_message @0212: "GET /shop/client_products_sorted/3/1/ HTTP/1.1" 200 3313
[INFO    :             django.server] - 2024-01-23 21:05:00,053 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3117
[INFO    :             django.server] - 2024-01-23 21:05:05,452 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5372
[INFO    :             django.server] - 2024-01-23 21:05:09,318 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3778
[INFO    :             django.server] - 2024-01-23 21:05:32,672 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 200 3313
[INFO    :   django.utils.autoreload] - 2024-01-23 21:08:49,401 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 21:10:15,086 : log_response @0241: Internal Server Error: /shop/client_orders/3
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 60, in client_orders
    products[order.id] = str(order.products.all()).replace('<QuerySet [<', '').replace('>]>',
AttributeError: 'Order' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-23 21:10:15,087 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 500 74948
[INFO    :   django.utils.autoreload] - 2024-01-23 21:11:13,744 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:11:14,433 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 21:11:18,184 : log_response @0241: Internal Server Error: /shop/client_orders/3
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 63, in client_orders
    return render(request, 'app_2/client_orders.html', {'client': client, 'orders': orders,
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: app_2/client_orders.html
[ERROR   :             django.server] - 2024-01-23 21:11:18,187 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 500 91653
[INFO    :             django.server] - 2024-01-23 21:13:43,108 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 3966
[INFO    :             django.server] - 2024-01-23 21:18:53,261 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 3989
[INFO    :             django.server] - 2024-01-23 21:22:36,842 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 3994
[INFO    :             django.server] - 2024-01-23 21:23:52,634 : log_message @0212: "GET /shop/orders HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 21:23:52,646 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3778
[INFO    :   django.utils.autoreload] - 2024-01-23 21:27:38,749 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:27:43,689 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3796
[INFO    :   django.utils.autoreload] - 2024-01-23 21:28:53,227 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:28:53,813 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 21:29:38,008 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:29:38,662 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:29:44,740 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 4012
[INFO    :             django.server] - 2024-01-23 21:30:35,606 : log_message @0212: "GET /shop/client_orders/1 HTTP/1.1" 200 3070
[INFO    :             django.server] - 2024-01-23 21:30:43,267 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 4012
[INFO    :   django.utils.autoreload] - 2024-01-23 21:31:19,483 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:31:20,141 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 21:38:27,102 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:38:34,689 : log_message @0212: "GET /shop/client_orders/5 HTTP/1.1" 200 4010
[INFO    :             django.server] - 2024-01-23 21:39:21,405 : log_message @0212: "GET /shop/client_products_sorted/5/0 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 21:39:21,414 : log_message @0212: "GET /shop/client_products_sorted/5/0/ HTTP/1.1" 200 3312
[INFO    :             django.server] - 2024-01-23 21:39:46,379 : log_message @0212: "GET /shop/client_products_sorted/5/1/ HTTP/1.1" 200 3312
[INFO    :             django.server] - 2024-01-23 21:39:57,630 : log_message @0212: "GET /shop/client_products_sorted/5/0/ HTTP/1.1" 200 3312
[INFO    :             django.server] - 2024-01-23 21:40:04,781 : log_message @0212: "GET /shop/client_products_sorted/5/2/ HTTP/1.1" 200 3312
[INFO    :   django.utils.autoreload] - 2024-01-23 21:42:57,767 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:42:58,357 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:43:26,154 : log_message @0212: "GET /shop/order/22 HTTP/1.1" 200 3018
[INFO    :             django.server] - 2024-01-23 21:45:33,416 : log_message @0212: "GET /shop/order/22 HTTP/1.1" 200 3095
[INFO    :   django.utils.autoreload] - 2024-01-23 21:50:02,225 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:50:02,953 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:50:04,380 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3117
[INFO    :   django.utils.autoreload] - 2024-01-23 21:50:40,047 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:50:40,662 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:51:59,218 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3122
[INFO    :             django.server] - 2024-01-23 21:52:41,282 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3133
[INFO    :             django.server] - 2024-01-23 21:53:16,883 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3104
[INFO    :             django.server] - 2024-01-23 21:53:24,277 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5380
[INFO    :             django.server] - 2024-01-23 21:53:32,775 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3794
[INFO    :             django.server] - 2024-01-23 21:53:38,470 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3104
[INFO    :             django.server] - 2024-01-23 21:53:42,132 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3794
[INFO    :             django.server] - 2024-01-23 21:53:51,401 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5380
[INFO    :             django.server] - 2024-01-23 21:53:55,144 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3104
[INFO    :   django.utils.autoreload] - 2024-01-23 21:56:27,220 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:56:53,723 : log_message @0212: "GET /shop/client_products_sorted/6/1 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 21:56:53,739 : log_message @0212: "GET /shop/client_products_sorted/6/1/ HTTP/1.1" 200 3190
[INFO    :             django.server] - 2024-01-23 21:57:09,859 : log_message @0212: "GET /shop/client_products_sorted/5/1/ HTTP/1.1" 200 3312
[INFO    :             django.server] - 2024-01-23 21:57:18,561 : log_message @0212: "GET /shop/client_products_sorted/5/0/ HTTP/1.1" 200 3312
[WARNING :            django.request] - 2024-01-23 21:57:27,494 : log_response @0241: Not Found: /shop/client_products_sorted/5/-1/
[WARNING :             django.server] - 2024-01-23 21:57:27,495 : log_message @0212: "GET /shop/client_products_sorted/5/-1/ HTTP/1.1" 404 3693
[INFO    :             django.server] - 2024-01-23 21:57:36,957 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3211
[INFO    :             django.server] - 2024-01-23 21:57:47,917 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5380
[INFO    :             django.server] - 2024-01-23 21:57:50,877 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 4190
[DEBUG   :               app_1.views] - 2024-01-23 21:58:06,787 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 21:58:06,787 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[INFO    :             django.server] - 2024-01-23 21:58:13,774 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3211
[INFO    :             django.server] - 2024-01-23 21:58:19,828 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3211
[INFO    :             django.server] - 2024-01-23 21:58:22,228 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5380
[INFO    :             django.server] - 2024-01-23 21:58:25,346 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 4190
[INFO    :             django.server] - 2024-01-23 21:58:28,923 : log_message @0212: "GET / HTTP/1.1" 200 3062
[INFO    :   django.utils.autoreload] - 2024-01-23 22:04:18,726 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 22:05:04,302 : log_message @0212: "GET /shop/client_orders/5 HTTP/1.1" 200 4010
